### ISSUE TITLE
Book: Finish tutorial

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/cli-wg#78]
Issue tracking progress of tutorial chapters

- Project setup
  - [x] draft
  - [x] ~~template: #53~~
  - [x] final review
- Parsing command line arguments
  - [x] draft
  - [x] ~~clap 3: #64~~
  - [x] final review
- First implementation
  - [x] draft
  - [x] first revision
  - [x] final review
- Nicer error reporting
  - [x] draft
  - [x] error context, failure: #65
  - [x] final review
- Output for humans and machines
  - [x] draft
  - [x] stderr #66
  - [x] progress bars #67
  - [x] logging #68
  - [x] final review
- Testing
  - [x] draft
  - [x] writing testable code #71
  - [x] assert_cli #72
  - [x] final review
- Packaging and distributing
  - [x] draft
  - [x] packaging #69
  - [x] ~~man pages (also shell completions) #70~~
  - [x] final review

**Comment by killercup** [comment]
further refinements in more specific issues
